blog/urls.py
# Stdlib imports

# Core Django imports
from django.conf.urls import url

# Third-party app imports

# Imports from apps
from . import views

app_name='blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^archive/', views.archive, name='archive'),
    url(r'^post/(?P<pk_post>\d+)/$', views.detail, name='detail'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    #url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'tasks/$', views.tasks, name='tasks'),
    url(r'the_study/$', views.the_study, name='the_study'),

    # ----------------
    #     The following url url messed with the setup of the ELSA archive directory, found in ELSA 
    #     project directory and online at https://atmos.nmsu.edu/elsa/archive/; hence, the issue.  
    #
    #     However, I left this url commented out because I learned about how to nest an argument in
    #     a url.
    #
    # url(r'^archive/(?:detail-(?P<pk>\d+)/)?$', views.detail, name='detail'),
        # (?: ... )? is an outer argument with a nested argument.
        # For more information on what is happening here please see 
        # Nested Arguments @ https://docs.djangoproject.com/en/1.11/topics/http/urls/
    #
    #
    # ----------------
]

elsa/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^accounts/', include('friends.urls')),
    url(r'^student_lair/', include('blog.urls')),
    url(r'^build/', include('build.urls')),
    url(r'^review/', include('review.urls')),
    url(r'^tutorial/', include('tutorial.urls')),
    #url(r'^build_a_bundle/(?P<pk_bundle>\d+)/contextquery/exist/', include('crawl_starbase.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.ARCHIVE_URL, document_root=settings.ARCHIVE_DIR)

friends/urls.py
from django.conf.urls import url
from . import views



app_name='friends'
urlpatterns = [
    #url(r'^$', views.FriendList.as_view(), name='friends'),
    url(r'^(?P<pk_user>\d+)/$', views.profile, name='profile'),
    url(r'^login/$', views.friend_login, name='login'),
    url(r'^logout/$', views.friend_logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<pk_user>\d+)/settings/$', views.friend_settings, name='settings'),

]

main/urls.py
"""
K. Sweebe

elsa.main.urls shows the listing of all current urls associated with elsa's main app.

"""

from django.conf.urls import url
from . import views

app_name='main'
urlpatterns = [

    # elsa's main views.
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^services/$', views.services, name='services'),
    url(r'^construction/$', views.construction, name='construction'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^error/$', views.error, name='error'),
    url(r'^restricted_access/$', views.restricted_access, name='restricted_access'),
    url(r'^simple_upload/$', views.simple_upload, name='simple_upload'),

    # I use this for development (k).
    url(r'^success/$', views.success, name='success'),
]

blog/models.py
# Stdlib imports
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime

# Core Django imports
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

# Third-party app imports

# Imports from apps

# Create your models here.



@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    overview = models.CharField(max_length=40)
    views = models.IntegerField(default=0)
    #likes = models.IntegerField(default=0)
#    slug = models.SlugField(unique=True)

#    def save(self, *args, **kwargs):
#        self.slug = slugify(self.name)
#        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=22)
    overview = models.CharField(max_length=40)
    content = models.TextField()
    category = models.ForeignKey(Category)
    date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

@python_2_unicode_compatible
class Comment(models.Model):
    author = models.ForeignKey(User)
    content = models.TextField(max_length=5000)
    date = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post)

    def __str__(self):
        shortened_content = self.content[:10]
        return '{0}: {1}'.format(self.author, shortened_content)

    def was_published_recently(self):
        return self.date >= timezone.now() - datetime.timedelta(days=1)


# To begin making a model, we need to dissect the structure of a Django Model Object.  Below is the skeleton for the Task model object.
#
#@python_2_unicode_compatible
#class Task(models.Model):	
#
#    # Attributes of your model are listed here.  The attributes do as normal attributes do and describe the object at hand.
#    # Each attribute is related to a model field reference.  The model field references are used in a number of places (forms, database, ..).
#
#
#

blog/forms.py
# Stdlib imports

# Core Django imports
from django import forms

# Third-party app imports

# Imports from apps
from .models import Post, Comment, Category

# Blog forms

class PostForm(forms.ModelForm):
    # PostForm behaves like a normal blog post with more or less features
    # than you would expect from a normal blog.

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content',)

class CategoryForm(forms.ModelForm):
    name = forms.CharField(help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    #likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

# This is forms.py where the Djnago forms live.  In models.py we saw a Task model object.  Here we are going to build an associated form.
# The basic structure is as follows...
#
# class TaskForm(forms.ModelForm)::
#     
#      # Attributes here 
#
#
#

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import user_passes_test, permission_required
from django.shortcuts import render, get_object_or_404
# Stdlib imports
import random

# Core Django imports
from django.utils import timezone

# Third-party app imports

# Imports from apps
from .forms import PostForm, CategoryForm
from .models import Post, Comment, Category
from main.models import Joke


# Secure page information here. ----------------
#     The following source talks about permission_required and the pass test decorator
#     source: https://docs.djangoproject.com/en/1.11/topics/auth/default/
#
#     The following source mentions a comment about group decorators.
#     source: https://bradmontgomery.net/blog/restricting-access-by-group-in-django/
#
#     The following source is a similar decorator definition and implementation.
#     source: https://gist.github.com/bradmontgomery/5657267
def atmos_student(function=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated() and u.groups.filter(name='Atmos Student').exists()
    )
    return actual_decorator(function)
#
#
#  End secure page information here. ----------------


# Create your views here. ----------------
#
#
# index is simply the homepage for the blog app.
@atmos_student
def index(request):
    post_list = Post.objects.order_by('date')[:3]
    category_list = Category.objects.order_by('-views')[:5]
    random_index = random.randint(0, Joke.objects.count()-1)
    random_joke = Joke.objects.all()[random_index]
    context_dict = {'posts':post_list, 'categories':category_list, 'joke':random_joke}
    return render(request, 'blog/index.html', context_dict)


# archive is a listing of all blog posts within ELSA.
@atmos_student
def archive(request):    
    posts = Post.objects.order_by('date')
    form = PostForm()
    if request.method == 'POST':
       form = PostForm(request.POST)
       if form.is_valid():
           post = form.save(commit=False) # means we do not want to save the Post model yet.
           post.user = request.user
           post.date = timezone.now()
           post.save()                    # and now we save
           return render(request, 'blog/archive.html', {'posts':posts})
    else:
        form = PostForm()
    return render(request, 'blog/archive.html', {'posts':posts,
                                                 'form':form,
                                                })

# detail shows a detailed display of each post.  I really wanted to call this post but I didn't know if there would be naming convention problems, so display it is (k).
# actually we should rename this to show_post (k).
@atmos_student
def detail(request, pk_post):
    context_dict = {}
    context_dict['post'] = Post.objects.get(pk=pk_post)
    context_dict['comment_list'] = Comment.objects.filter(post=pk_post)
    return render(request, 'blog/detail.html', context_dict )


# show_category shows a single category and it's related posts.
@atmos_student
def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        post = Post.objects.filter(category=category)
        context_dict['post'] = post
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['post'] = None
    return render(request, 'blog/category.html', context_dict)


@atmos_student
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=True)
            print(cat, cat.slug)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'blog/add_category.html', {'form':form})


@atmos_student
def add_post(request):
    return render(request, 'blog/add_post.html', {})

@atmos_student
def tasks(request):
    return render(request, 'blog/tasks.html', {})

@atmos_student
def the_study(request):

    return render(request, 'blog/the_study.html', {})

templates/blog/add_category.html
{% extends 'blog/base-k.html' %}
{% load staticfiles %}

{% block title_block%}
    {{ 'Add a Category' }}
{% endblock %}


{% block body_block %}
    <h1>Add a Category</h1>
      <form id="category_form" method="post" action="{% url 'blog:add_category' %}">
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
              {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields  %}
              {{ field.errors }}
              {{ field.help_text }}
              {{ field }}
          {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
      </form>


{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="ELSA is an educational tool used at NASA PDS's Atmospheres node for creating PDS4 compliant labels for data bundles.">
    <meta name="author" content="NMSU Atmos Students">
    <link rel="icon" href="<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>ELSA - {% block title_block %}Educational Labeling System @Atmospheres{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <link href="{% static 'css/elsa-css.css/' %}" rel="stylesheet" type="text/css">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'elsa:index' %}">ELSA: Educational Labeling System @Atmospheres</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'elsa:index' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'elsa:build' %}">Bundle</a>
          </li>
          <!--
          <li role="presentation" class="dropdown">              
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'elsa:build' %}" role="baria-haspopup="true" aria-expanded="false">Bundle</a><span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'build_a_bundle:index' %}">Build</a></li>
                <li><a href="{% url 'search_a_bundle:index' %}">Search</a></li>
                <li><a href="{% url 'elsa:error' %}">Review</a></li>
                <li><a href="{% url 'elsa:error' %}">Submit</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'elsa:error' %}">Tutorial</a></li>
              </ul>
          </li>
          -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'elsa:contact' %}">Contact</a> <!-- EVENTUALLY DELETE -->
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'elsa:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'elsa:register' %}">Sign Up</a> <!-- EVENTUALLY DELETE -->
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'elsa:login' %}">Log In</a> <!-- EVENTUALLY DELETE -->
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'elsa:contact' %}">Contact</a> <!-- EVENTUALLY DELETE -->
          </li>
          {% endif %}

        </ul>

      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="#">Welcome, {{ user.name }} <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:archive' %}">Blog Archive</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:add_category' %}">Add Category</a>
            </li>
            {% endif %}

          </ul>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            <h3>
            {% block header_block %}{% endblock %}
            </h3>
            <hr>
            {% block body_block %}{% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/blog/carousel-k.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>ELSA: {% block title_block %}Educational Labeling System @Atmospheres{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/blog-style.css' %}" rel="stylesheet">
</head>

<body>

    <!-- Start your project here-->
    <header>

        <!--Navbar-->
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark elegant-color-dark">

            <!-- Navbar brand -->
            <a class="navbar-brand" href="{% url 'main:index' %}">
                <i id="icon" class="fa fa-snowflake-o" style="text-shadow: none; font-size: 25px; color: rgb(43, 187, 173); height: 30px; width: 30px; line-height: 30px; border-radius: ; text-align: center; background-color: rgb(46, 46, 46);"></i> 
                ELSA
             </a>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#"><i class="fa fa-snowflake-o" aria-hidden="true"></i> About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'build:index' %}"><i class="fa fa-briefcase"></i> Bundle</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:index' %}"><i class="fa fa-newspaper-o"></i> Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}"><i class="fa fa-envelope"></i> Contact</a>
                    </li>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{ user }}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{{ user.userprofile.get_absolute_url }}">{{ user.first_name }}'s Profile</a>
                            <a class="dropdown-item" href="{% url 'main:construction' %}">ELSA Tutorial</a>
                            <a class="dropdown-item" href="{% url 'main:construction' %}">Profile Settings</a>
                            <a class="dropdown-item" href="{% url 'friends:logout' %}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'friends:register' %}"><i class="fa fa-hand-spock-o" aria-hidden="true"></i> Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'friends:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}"><i class="fa fa-envelope"></i> Contact</a>
                    </li>
                    {% endif %}

                </ul>
                <!-- Links -->
            </div>
            <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->  



<!--Carousel Wrapper-->
<div id="carousel-example-3" class="carousel slide carousel-fade white-text" data-ride="carousel" data-interval="false">
    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-3" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-3" data-slide-to="1"></li>
        <li data-target="#carousel-example-3" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <!-- First slide -->
        <div class="carousel-item active view hm-black-light">

            <!-- Caption -->
            <div class="full-bg-img flex-center white-text">
                <ul class="animated fadeInUp col-md-12">
                    {% block carousel_one_block %}
                    {% endblock %}  
                </ul>
            </div>
            <!-- /.Caption -->
        </div>
        <!-- /.First slide -->
        <!-- Second slide -->
        <div class="carousel-item view hm-black-light">

            <!-- Caption -->
            <div class="full-bg-img flex-center white-text">
                <ul class="animated fadeInUp col-md-12">
                    {% block carousel_two_block %}

                    {% endblock %}
                </ul>
            </div>
            <!-- /.Caption -->
        </div>
        <!-- /.Second slide -->
        <!-- Third slide -->
        <div class="carousel-item view hm-black-light">

            <!-- Caption -->
            <div class="full-bg-img flex-center white-text">
                <ul class="animated fadeInUp col-md-12">
                    {% block carousel_three_block %}

                    {% endblock %}
                </ul>
            </div>
            <!-- /.Caption -->
        </div>
        <!-- /.Third slide -->
    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-3" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
</a>
    <a class="carousel-control-next" href="#carousel-example-3" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
</a>
    <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->
             


            
    </header>
    <!--/.Header-->




    <!--Main layout-->
    <main>
        <div class="container-fluid">

            <!--Your content goes here-->

            <!--Your content goes here-->

        </div>
    </main>
    <!--Main layout-->


    <!--Footer-->
    <footer class="page-footer elegant-color center-on-small-only"> <!-- fixed-bottom class-->

        <!--Footer Links-->
        <div class="container">
            <div class="row">

                <!--First column-->
                <div class="col-md-6">
                    <a href="{% url 'main:index' %}">
                    <h6 class="title">
 <i id="icon" class="fa fa-snowflake-o" style="text-shadow: rgb(32, 32, 32) 0px 0px 0px, rgb(33, 33, 33) 1px 1px 0px, rgb(34, 34, 34) 2px 2px 0px, rgb(35, 35, 35) 3px 3px 0px, rgb(35, 35, 35) 4px 4px 0px, rgb(36, 36, 36) 5px 5px 0px, rgb(37, 37, 37) 6px 6px 0px, rgb(38, 38, 38) 7px 7px 0px, rgb(38, 38, 38) 8px 8px 0px, rgb(39, 39, 39) 9px 9px 0px, rgb(40, 40, 40) 10px 10px 0px, rgb(41, 41, 41) 11px 11px 0px, rgb(41, 41, 41) 12px 12px 0px, rgb(42, 42, 42) 13px 13px 0px, rgb(43, 43, 43) 14px 14px 0px, rgb(44, 44, 44) 15px 15px 0px, rgb(44, 44, 44) 16px 16px 0px, rgb(45, 45, 45) 17px 17px 0px; font-size: 50px; color: rgb(43, 187, 173); height: 107px; width: 107px; line-height: 107px; border-radius: ; text-align: center; background-color: rgb(46, 46, 46);"></i> 
                    Educational Labeling System @Atmospheres
                    </a>
                    </h6>
                </div>
                <!--/.First column-->



                <!--Second column-->

                <div class="col-md-6">
                    <h6 class="title">
                    <a href="http://atmos.nmsu.edu/">
 
 <i id="icon" class="fa fa-cloud" style="text-shadow: rgb(32, 32, 32) 0px 0px 0px, rgb(33, 33, 33) 1px 1px 0px, rgb(34, 34, 34) 2px 2px 0px, rgb(35, 35, 35) 3px 3px 0px, rgb(35, 35, 35) 4px 4px 0px, rgb(36, 36, 36) 5px 5px 0px, rgb(37, 37, 37) 6px 6px 0px, rgb(38, 38, 38) 7px 7px 0px, rgb(38, 38, 38) 8px 8px 0px, rgb(39, 39, 39) 9px 9px 0px, rgb(40, 40, 40) 10px 10px 0px, rgb(41, 41, 41) 11px 11px 0px, rgb(41, 41, 41) 12px 12px 0px, rgb(42, 42, 42) 13px 13px 0px, rgb(43, 43, 43) 14px 14px 0px, rgb(44, 44, 44) 15px 15px 0px, rgb(44, 44, 44) 16px 16px 0px, rgb(45, 45, 45) 17px 17px 0px; font-size: 50px; color: rgb(43, 187, 173); height: 107px; width: 107px; line-height: 107px; border-radius: ; text-align: center; background-color: rgb(46, 46, 46);"></i> 
                    Planetary Armospheres Node
                    </a>
                    </h6>
                </div>
                <!--/.Second column-->
            </div>
        </div>
        <!--/.Footer Links-->

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container">
                © 2015 Copyright: <a href="{% url 'main:index' %}"> ELSA.com </a>
            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- ELSA JavaScript -->
    <script type="text/javascript" src="{% static 'js/elsa-help.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'js/elsa-todo.js' %}"></script>-->
    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/dc496c8662.js"></script>

</body>

</html>

templates/blog/category.html
{% extends 'blog/base-k.html' %}
{% load staticfiles %}

{% block title_block%}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
      <h1>{{ category.name }} </h1>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>
            <hr />
            <h2>Want to add a page to this category?</h2>
            <a href="{% url 'blog:add_page' category.slug %}">Add Page</a>
            <hr />            
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
    {% endif %}
{% endblock %}